services:
  - type: web
    name: library-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: run
        sync: false
      - key: NODE_ENV
        value: production
